### ISSUE TITLE
Mistake using modulus operator

### ISSUE THREAD

**Issue by KCEvers** [r-quantities/units#377] opened 2024-10-08 13:28 UTC
Hi all,

There seems to be a mistake when using the modulus operator:

units::set_units(12.25, "hour") %% 24
-11.75 [h]

Could this be fixed? Thanks!

Best, Kyra

**Comment by Enchufa2** [comment] 2024-10-08 13:40
Sorry, I cannot reproduce this. I see:

``` r
units::set_units(12.25, "hour") %% 24
#> 12.25 [h]
```

Are you running an up-to-date version of the package?

**Comment by Enchufa2** [comment] 2024-10-08 13:50
Oh, yes, this was fixed in #365, but not yet on CRAN. It will be part of the next update. Thanks for the report.

**Closed by Enchufa2** 2024-10-08 13:50 UTC
Labels: duplicate

**Comment by KCEvers** [comment] 2024-10-09 20:41
Great, thank you for looking into it!
